/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-08-07 19:00:49 UTC)
 * on 2013-08-13 at 18:32:26 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.smartmeetings.model;

/**
 * Model definition for Room.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the . For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Room extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Building building;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer floorSpace;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String label;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer numberOfSeats;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String roomNumber;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String uri;

  /**
   * @return value or {@code null} for none
   */
  public Building getBuilding() {
    return building;
  }

  /**
   * @param building building or {@code null} for none
   */
  public Room setBuilding(Building building) {
    this.building = building;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getFloorSpace() {
    return floorSpace;
  }

  /**
   * @param floorSpace floorSpace or {@code null} for none
   */
  public Room setFloorSpace(java.lang.Integer floorSpace) {
    this.floorSpace = floorSpace;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLabel() {
    return label;
  }

  /**
   * @param label label or {@code null} for none
   */
  public Room setLabel(java.lang.String label) {
    this.label = label;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getNumberOfSeats() {
    return numberOfSeats;
  }

  /**
   * @param numberOfSeats numberOfSeats or {@code null} for none
   */
  public Room setNumberOfSeats(java.lang.Integer numberOfSeats) {
    this.numberOfSeats = numberOfSeats;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getRoomNumber() {
    return roomNumber;
  }

  /**
   * @param roomNumber roomNumber or {@code null} for none
   */
  public Room setRoomNumber(java.lang.String roomNumber) {
    this.roomNumber = roomNumber;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUri() {
    return uri;
  }

  /**
   * @param uri uri or {@code null} for none
   */
  public Room setUri(java.lang.String uri) {
    this.uri = uri;
    return this;
  }

  @Override
  public Room set(String fieldName, Object value) {
    return (Room) super.set(fieldName, value);
  }

  @Override
  public Room clone() {
    return (Room) super.clone();
  }

}
