/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-08-07 19:00:49 UTC)
 * on 2013-08-13 at 18:32:26 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.smartmeetings.model;

/**
 * Model definition for SensorData.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the . For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class SensorData extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer humidity;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer pressure;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String roomURI;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer temperature;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getHumidity() {
    return humidity;
  }

  /**
   * @param humidity humidity or {@code null} for none
   */
  public SensorData setHumidity(java.lang.Integer humidity) {
    this.humidity = humidity;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getPressure() {
    return pressure;
  }

  /**
   * @param pressure pressure or {@code null} for none
   */
  public SensorData setPressure(java.lang.Integer pressure) {
    this.pressure = pressure;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getRoomURI() {
    return roomURI;
  }

  /**
   * @param roomURI roomURI or {@code null} for none
   */
  public SensorData setRoomURI(java.lang.String roomURI) {
    this.roomURI = roomURI;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getTemperature() {
    return temperature;
  }

  /**
   * @param temperature temperature or {@code null} for none
   */
  public SensorData setTemperature(java.lang.Integer temperature) {
    this.temperature = temperature;
    return this;
  }

  @Override
  public SensorData set(String fieldName, Object value) {
    return (SensorData) super.set(fieldName, value);
  }

  @Override
  public SensorData clone() {
    return (SensorData) super.clone();
  }

}
